# Generated by Django 4.1.5 on 2023-05-12 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_formdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Addstudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=500)),
                ("semail", models.EmailField(max_length=254)),
                ("smonile", models.IntegerField()),
                ("saddress", models.CharField(max_length=1000)),
                ("scollege", models.CharField(max_length=500)),
                ("sdegree", models.CharField(max_length=500)),
                ("total_amount", models.IntegerField()),
                ("paid_amount", models.IntegerField()),
                ("due_amount", models.FloatField()),
                (
                    "scourse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.addcourses",
                    ),
                ),
            ],
        ),
    ]
